# Define input channels.
train_dir: '/mnt/share/raheppt1/MelanomCT_Organ/'
validation_split: 40

images:
  -
    name: ct
    pattern: '**/*ct*3mm_low.nii*'

# Define labels.
labels:
  - name: liver
    pattern: '**/*liver*3mm_low.nii*'
    prob: 0.3
  -
    name: spleen
    pattern: '**/*spleen*3mm_low.nii*'
    prob: 0.2
  -
    name: spine
    pattern: '**/*spine*3mm_low.nii*'
    prob: 0.2


# Model configuration and path to save checkpoints:
model_path: '/mnt/share/raheppt1/pytorch_models/seg'
model:
  in_channels: 1
  out_channels: 4 # including one channel for the background!
  f_maps: 64

# Tensorboard logging:
run: ctorgan
log_dir: './runs'
print_interval: 10

# Dataloading:
patch_size: [96, 96, 96]
train_batchsize: 4
eval_batchsize: 4
queue:
  max_length: 300
  samples_per_volume: 30
  num_workers: 15
  shuffle_subjects: False
  shuffle_patches: True

# Training parameters:
learning_rate: 0.0001
max_epochs: 300
loss: 'DICE' # in ['DICE', 'CE']

# work_dir = Path('/mnt/share/raheppt1/MelanomCT_Organ/')
#path_labels = list(work_dir.glob('**/*liver_3mm_low*'))
#path_labels2 = list(work_dir.glob('**/*spleen_3mm_low*'))
#path_images = list(work_dir.glob('**/*ct_3mm_low*'))
