# Define input channels.
train_dir: '/mnt/share/raheppt1/BClesions/tumor/'
test_dir: '/mnt/share/raheppt1/BClesions/tumor/'
validation_split: 200

images:
  -
    name: pet
    pattern: '**/*petsuv*nii*'
  -
    name: ct
    pattern: '**/*rs*ct*nii'

# Define labels.
labels:
  -
    name: tumor
    pattern: '**/iso*tumor*'
    prob: 0.5

# Model configuration and path to save checkpoints:
model_path: '/mnt/share/raheppt1/pytorch_models/seg'
model:
  in_channels: 2
  out_channels: 2 # including one channel for the background!
  f_maps: 64

# Tensorboard logging:
run: petbc
log_dir: './runs'
print_interval: 10

# Dataloading:
patch_size: [96, 96, 96]
train_batchsize: 4
eval_batchsize: 4
queue:
  max_length: 300
  samples_per_volume: 30
  num_workers: 15
  shuffle_subjects: False
  shuffle_patches: True

# Training parameters:
learning_rate: 0.0001
max_epochs: 300
loss: 'DICE' # in ['DICE', 'CE']