eval:
  batch_size: 4
  queue:
    max_length: 300
    num_workers: 0
    samples_per_volume: 30
    shuffle_patches: true
    shuffle_subjects: false
learning_rate: 0.0001
log_dir: ./runs
max_epochs: 300
model:
  fmaps: 64
  in_channels: 1
  out_channels: 3
model_path: /mnt/share/raheppt1/pytorch_models
patch_size: !!python/tuple
- 96
- 96
- 96
print_interval: 10
train:
  batch_size: 4
  queue:
    max_length: 300
    num_workers: 0
    samples_per_volume: 30
    shuffle_patches: true
    shuffle_subjects: false
